# Generated by Django 4.0.3 on 2023-11-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('city', models.TextField()),
                ('sub', models.TextField()),
            ],
        ),
    ]
